apiVersion: v2
appVersion: v0.5.1
description: 'Topology-aware NRI resource policy plugin is a NRI plugin that will
  apply hardware-aware resource allocation policies to the containers running in the
  system. '
home: https://github.com/containers/nri-plugins
name: nri-resource-policy-topology-aware
sources:
- https://github.com/containers/nri-plugins
type: application
version: v0.5.1
