apiVersion: v1
entries:
  nri-resource-policy-topology-aware:
  - apiVersion: v2
    appVersion: v0.5.1
    created: "2024-05-10T16:50:17.954460024-05:00"
    description: 'Topology-aware NRI resource policy plugin is a NRI plugin that will
      apply hardware-aware resource allocation policies to the containers running
      in the system. '
    digest: 01d868520805e94b5fbec0acafcb18eb222e857dae777b4131761a2df80a36aa
    home: https://github.com/wongchar/nri-plugins
    name: nri-resource-policy-topology-aware
    sources:
    - https://github.com/wongchar/nri-plugins
    type: application
    urls:
    - https://github.com/wongchar/nri-plugins/tree/llc/deployment/helm/nri-resource-policy-topology-aware-v0.5.1.tgz
    version: v0.5.1
generated: "2024-05-10T16:50:17.953782357-05:00"
